version: 2.1

jobs:
  build:
    docker:
      # Using a CircleCI-maintained Python image
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd HW03a
            python -m pip install --upgrade pip
            pip install requests
      - run:
          name: Run Unit Tests
          command: python -m unittest HW03a/test.py
